name: CI
on:
  push:
    branches: ['develop', 'master']
jobs:
  devops:
    name: Build, Unit Test and SonarCloud Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: {fetch-depth: 0}
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Unit & Integration Tests
        run: mvn clean install
      - name: Sonar
        if: success() # always() failure() success()
        run: >
          mvn -B verify -DskipTests sonar:sonar
          -Dsonar.projectKey=com.example:autoclaim
          -Dsonar.organization=harsh-pmb
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.login=$SONAR_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
