name: cicd

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Maven Build
      run: mvn clean install
      
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Run unit test
      run: mvn test -Dmaven.test.failure.ignore=true
