name: cicd

on: [push]

env: 
     MAVEN_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/repository"

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: "${{ github.workspace }}/repository"
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
      
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Maven Build
      run: mvn clean install -DskipTests=true
      
    - name: Send Notification
      uses: fjogeleit/http-request-action@master
      with:
        url: '${{ secrets.SN_INSTANCE_URL }}/api/sn_devops/devops/onboarding/app'
        method: 'POST'
        contentType: 'application/json'
        username: ${{ secrets.SN_DEVOPS_USER }}
        password: ${{ secrets.SN_DEVOPS_PASSWD }}
        data: '{"apps":[{"id":"602252962067","nativeId":"602252962067","name": "Workspace 11::Seventh Project","url":"https://rally1.rallydev.com/slm/webservice/v2.x/project/602252962067","toolId":"d510bba91b5d7050b9df4338b04bcb6c","tool":"d510bba91b5d7050b9df4338b04bcb6c","track":"true"}]}'
