name: cicd

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Maven Build
      run: mvn clean install -DskipTests=true
    - name: Run Unit Tests
      run: mvn test -Dmaven.test.failure.ignore=true -DskipTests=false
      
  report:
      name: Publish Unit Test Report
      needs: build
      runs-on: ubuntu-latest
      steps:
      - uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/TEST-*.xml'
